### ISSUE TITLE
The canvas is outdated

### ISSUE THREAD

**Issue by Wendelstein7** [Codixer/place-atlas#325]
Hi there! This is a very nice wonderful project and I've submitted a few additions myself aswell.

However, I noticed that the current image at https://place-atlas.stefanocoding.me/ of the 2022 r/place isn't the most recent image that's available. There's pictures on the internet that are more recent (closer to the white void, without including the white void.)

This one I've seen around a lot, it's newer and it actually features some minor and major developments that happened after the image currently in atlas was taken.

![image](https://user-images.githubusercontent.com/23213464/161716760-0c8fcb08-a8c7-49c7-98e1-fd21bfc5f7b7.png)

Therefore, I'd like to suggest to perhaps use the newer image I included! I would've created a PR, but I thought I'd open an issue for discussion here first.

Thanks!

**Comment by Wendelstein7** [comment]
I've since been informed of r/thefinalclean! 

Perhaps it'd be nice to replace the image now with https://www.reddit.com/r/place/comments/twhrf4/final_rplace_2022_canvas_before_my_scraper/ (as seen in PR #144 ) to assist in making notes and drawing regions...

...and later with a finalclean version from https://www.reddit.com/r/thefinalclean/

**Comment by n9iels** [comment]
Or even better: https://www.reddit.com/r/place/comments/twjxyp/place_30_seconds_before_destruction_now_in_8k

**Comment by tocram1** [comment]
Some artwork really got badly destroyed around the last hours, maybe it could be a good idea ta take a screenshot before that (eg. the french artwork at the bottom left hand corner, some middle right artwork as well if I remember correctly).
Just my opinion though, I'd agree that this makes it a bit outdated as lots of things happened after that.

**Comment by tauin** [comment]
I think the dream solution would be the possibility of a timeline/video/scrub through of the atlas (e.g a little slider at the top, left is the first second of r/place and right is the white out)

The original r/place atlas has images atlases that where completely covered (like the green corner) so this seems to be a natural extension of what the r/place atlas should be.

unfortunately that makes this project orders of magnitude more difficult as its far more complex (although r/place is popular enough to where you could probably post on reddit somewhere for help and you'd get some web devs)

**Comment by tauin** [comment]
the true endgame is actually having a sort of wiki detailing history behind certain artwork, showing concept art and revisions and detailing alliances.
