### ISSUE TITLE
id: twn7x2 mispelling in title

### ISSUE THREAD

**Issue by Themis3000** [Codixer/place-atlas#398]
On the entry with the id #twn7x2, there is a misspelling in the title. The title says "Scratch from The Ghost and Molly Magee", but it should say "Scratch from The Ghost and Molly Mcgee" (Mcgee instead of Magee).

In the body text of the entry you can see Magee is later spelled correctly as Mcgee. The Ghost and Molly Mcgee is a tv show, so I'm sure that spelling it correct. Someone within the community pointed it out.

Let me know if this is the correct place to submit something like this or if I should take this elsewhere. Thank you!

**Comment by ab-gh** [comment]
https://github.com/Codixer/place-atlas/commit/b6f89ad957d96b50bdfc4f9f5620cd4a8714652d
