### ISSUE TITLE
Wrong card for french flag

### ISSUE THREAD

**Issue by hecht-a** [Codixer/place-atlas#402]
![image](https://user-images.githubusercontent.com/50453254/161761162-ca58f1e7-42c3-4b12-ac2a-9654a129a5ce.png)

"A bot generated France flag" is fully wrong. We just used overlays to put pixel at the right place

**Comment by ann4belle** [comment]
Overlays wouldn't cause your flag to immediately be covered in white pixels when that change rolled out.

**Comment by fmoraldo-mithraw** [comment]
> Overlays wouldn't cause your flag to immediately be covered in white pixels when that change rolled out.

No, it was a horde of angry frenchmen "spamclicking" their assigned pixels 
Organisation and rally, that's what make the french gather 10M€ for online charity event like the ZEvent...
