### ISSUE TITLE
Wrong handling of \n

### ISSUE THREAD

**Issue by adri326** [Codixer/place-atlas#410]
It looks like the `\n` in the JSON that got posted in the subreddit were accidentally turned into regular `n`, resulting in many descriptions stemming from reddit to have stray `n`s in them.

**Comment by nico-abram** [comment]
Could someone assign this to me?

**Comment by nico-abram** [comment]
Should be fixed on https://github.com/Codixer/place-atlas/pull/548
Note: DOES NOT FIX THINGS RETROACTIVELY, ONLY FOR NEW SUBMISSIONS
