### ISSUE TITLE
id: twugx8 misspelling

### ISSUE THREAD

**Issue by RandomSebas** [Codixer/place-atlas#447]
![image](https://user-images.githubusercontent.com/63163980/161798170-08c87a0d-f56c-44e3-a00e-8dab2fc31602.png)

Columbia is a city in south Carolina, but that is the flag of the country in latam, colombia, its a common misspelling between americans

**Comment by ab-gh** [comment]
https://github.com/Codixer/place-atlas/commit/a49ffd1cb8c037b0907dcb7764d01b08f6aa2ff7
