### ISSUE TITLE
Wrong Mark of Diana Painting 

### ISSUE THREAD

**Issue by 0x7FFFFF** [Codixer/place-atlas#454]
Our Diana painting was marked wrongly by r/GreenLattice. Please correct this mistake.
![Screenshot_20220406-003057](https://user-images.githubusercontent.com/29014446/161802435-75d87fb1-f5e0-45b1-ab7d-be8f53461926.jpg)

**Comment by ab-gh** [comment]
Thanks for the contribution! To make merging easier for us, please resubmit this as a PR to the `/cleanup` branch.
