### ISSUE TITLE
Groups of multiple polygons draw borders across the canvas

### ISSUE THREAD

**Issue by Fasteroid** [Codixer/place-atlas#504]
Such as entry `000194` _"r/place Vtubers"_:

![image](https://user-images.githubusercontent.com/29342750/161829253-945492e0-bec8-4cf2-9a12-a5efc81fd456.png)

I know you are currently very busy, so I'm going to make a fork and fix this for you.
Keep up the hard work, Stefano.

**Comment by Fasteroid** [comment]
Oh no, that entry actually doesn't have any distinction between the polygons within it... bad data.  Not sure this is fixable.

**Comment by Codixer** [comment]
Solved in #511

**Comment by Fasteroid** [comment]
I'm making progress, should I stop?  I found a way to make the line drawer skip the duplicated points that cause this.

**Comment by Fasteroid** [comment]
Eh, forget it, sanitizing user data is a losing battle.
