### ISSUE TITLE
Longer title <h1> text is blocking buttons

### ISSUE THREAD

**Issue by Wayland-Smithy** [Codixer/place-atlas#523]
![brave_JE1rrZScFU](https://user-images.githubusercontent.com/64715958/161843205-b9803752-4738-43f9-9a06-1cbad0374e5e.gif)

**Comment by Wayland-Smithy** [comment]
Fixed with #518

**Comment by Codixer** [comment]
:D

**Comment by maltejur** [comment]
@Wayland-Smithy does the same thing happen on this page: https://deploy-preview-443--place-atlas.netlify.app/ ?

**Comment by Wayland-Smithy** [comment]
@maltejur Looks good on my machine. Best of both worlds!
