### ISSUE TITLE
Update request: Image of the map

### ISSUE THREAD

**Issue by UnRealDinnerbone** [Codixer/place-atlas#527]
The image in the atlas is not the last version the /r/place
there are some last-minute changes there happened that did not make onto the map
you can see for example the stargate logo does not have Mckay on the top of it

Reddit final version https://twitter.com/Reddit/status/1511383937305751555

**Comment by AfroThundr3007730** [comment]
Indeed, we should have the official latest version recorded in the atlas.

**Comment by ab-gh** [comment]
We'll have an update for you about this within the next few days 👍
